name: rosettapipeline
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - filechunkio=1.6=py36_0
  - ftputil=3.2=py36_0
  - pyasn1-modules=0.0.5=py36_0
  - pygraphviz=1.3.1=py36_0
  - pysftp=0.2.9=py36_0
  - rsa=3.1.4=py36_0
  - snakemake=5.3.0=2
  - snakemake-minimal=5.3.0=py_2
  - urllib3=1.12=py36_0
  - aioeasywebdav=2.2.0=py36_0
  - aiohttp=3.4.4=py36h470a237_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_1003
  - async-timeout=3.0.1=py_1000
  - attrs=18.2.0=py_0
  - bcrypt=3.1.4=py36h470a237_0
  - boto3=1.7.84=py_0
  - botocore=1.10.84=py_0
  - ca-certificates=2018.11.29=ha4d7672_0
  - cachetools=2.1.0=py_0
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h5e8e0c9_1
  - chardet=3.0.4=py36_1003
  - configargparse=0.13.0=py_1
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - curl=7.63.0=h74213dd_0
  - decorator=4.3.0=py_0
  - docutils=0.14=py36_1001
  - dropbox=7.3.1=py36_0
  - expat=2.2.5=hfc679d8_2
  - gettext=0.19.8.1=h5e8e0c9_1
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.56.2=h464dc38_1
  - gmp=6.1.2=hfc679d8_0
  - google-auth=1.2.1=py_0
  - google-auth-httplib2=0.0.3=py_2
  - google-cloud-core=0.24.1=py36_0
  - google-cloud-storage=1.1.1=py36_0
  - google-resumable-media=0.0.2=py36_0
  - googleapis-common-protos=1.5.5=py_0
  - graphite2=1.3.12=hfc679d8_1
  - httplib2=0.12.0=py36_1000
  - icu=58.2=hfc679d8_0
  - idna=2.8=py36_1000
  - idna_ssl=1.0.0=0
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9c=h470a237_1
  - jsonschema=3.0.0a3=py36_1000
  - krb5=1.16.2=hbb41f41_0
  - libarchive=3.3.3=h823be47_0
  - libcurl=7.63.0=hbdb9355_0
  - libedit=3.1.20170329=haf1bffa_1
  - libffi=3.2.1=hfc679d8_5
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h470a237_3
  - libpng=1.6.36=ha92aebf_0
  - libprotobuf=3.6.1=hd28b015_0
  - libssh2=1.8.0=h5b517e9_3
  - libtiff=4.0.10=he6b73bb_0
  - libtool=2.4.6=h470a237_2
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - markupsafe=1.1.0=py36h470a237_0
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - multidict=4.5.1=py36h470a237_0
  - ncurses=6.1=hfc679d8_1
  - networkx=2.2=py_1
  - openssl=1.0.2p=h470a237_1
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.5=0
  - paramiko=2.4.2=py36_1000
  - pcre=8.41=hfc679d8_3
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - prettytable=0.7.2=py_2
  - protobuf=3.6.1=py36hfc679d8_1
  - psutil=5.4.8=py36h470a237_0
  - pthread-stubs=0.4=h470a237_1
  - pyasn1=0.4.4=py_1
  - pycparser=2.19=py_0
  - pynacl=1.3.0=py36h470a237_0
  - pyrsistent=0.14.7=py36h470a237_0
  - python=3.6.7=h5001a0f_1
  - python-dateutil=2.7.5=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2018.7=py_0
  - pyyaml=3.13=py36h470a237_1
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=haf1bffa_1
  - requests=2.13.0=py36_0
  - s3transfer=0.1.13=py36_1001
  - setuptools=40.6.2=py36_0
  - six=1.11.0=py36_1001
  - smmap2=2.0.5=py_0
  - sqlite=3.26.0=hb1c47c0_0
  - tk=8.6.9=ha92aebf_0
  - wheel=0.32.3=py36_0
  - wrapt=1.10.11=py36h470a237_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxpm=3.5.12=h470a237_2
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-libxt=1.1.5=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - yarl=1.2.6=py36h470a237_0
  - zlib=1.2.11=h470a237_3
  - beautifulsoup4=4.6.3=py36_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h7636065_2
  - conda=4.5.11=py36_0
  - conda-build=3.17.3=py36_0
  - conda-env=2.6.0=1
  - datrie=0.7.1=py36h7b6447c_1
  - filelock=3.0.10=py36_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - gfortran_impl_linux-64=7.2.0=hdf63c60_3
  - gfortran_linux-64=7.2.0=h550dcbe_27
  - glob2=0.6=py36_1
  - graphviz=2.40.1=h25d223c_0
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - harfbuzz=1.7.6=h5f0a787_1
  - intel-openmp=2019.1=144
  - libgcc-ng=8.2.0=hdf63c60_1
  - liblief=0.9.0=h7725739_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - mkl=2018.0.3=1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - pango=1.41.0=hd475d92_0
  - patchelf=0.9=he6710b0_3
  - pkginfo=1.4.2=py36_1
  - py-lief=0.9.0=py36h7725739_1
  - pycosat=0.6.3=py36h14c3975_0
  - pyopenssl=18.0.0=py36_0
  - python-libarchive-c=2.8=py36_6
  - r-assertthat=0.2.0=mro343h889e2dd_0
  - r-bh=1.65.0_1=mro343h889e2dd_0
  - r-bindr=0.1=mro343h889e2dd_0
  - r-bindrcpp=0.2=mro343h599a50d_0
  - r-broom=0.4.3=mro343h889e2dd_0
  - r-callr=1.0.0=mro343h889e2dd_0
  - r-cellranger=1.1.0=mro343h889e2dd_0
  - r-cli=1.0.0=mro343h889e2dd_0
  - r-clipr=0.4.0=mro343h889e2dd_0
  - r-colorspace=1.3_2=mro343h086d26f_0
  - r-crayon=1.3.4=mro343h889e2dd_0
  - r-dbi=0.7=mro343h889e2dd_0
  - r-dbplyr=1.1.0=mro343h889e2dd_0
  - r-dichromat=2.0_0=mro343h889e2dd_0
  - r-dplyr=0.7.4=mro343h599a50d_0
  - r-forcats=0.2.0=mro343h889e2dd_0
  - r-ggplot2=2.2.1=mro343h889e2dd_0
  - r-glue=1.2.0=mro343h086d26f_0
  - r-gtable=0.2.0=mro343h889e2dd_0
  - r-haven=1.1.0=mro343h599a50d_0
  - r-hms=0.4.0=mro343h889e2dd_0
  - r-httr=1.3.1=mro343h889e2dd_0
  - r-labeling=0.3=mro343h889e2dd_0
  - r-lazyeval=0.2.1=mro343h086d26f_0
  - r-lubridate=1.7.1=mro343h599a50d_0
  - r-mnormt=1.5_5=mro343h4829c52_0
  - r-modelr=0.1.1=mro343h889e2dd_0
  - r-munsell=0.4.3=mro343h889e2dd_0
  - r-openssl=0.9.9=mro343h086d26f_0
  - r-pillar=1.0.1=mro343h889e2dd_0
  - r-pkgconfig=2.0.1=mro343h889e2dd_0
  - r-plogr=0.1_1=mro343h889e2dd_0
  - r-plyr=1.8.4=mro343h599a50d_0
  - r-psych=1.7.8=mro343h889e2dd_0
  - r-purrr=0.2.4=mro343h086d26f_0
  - r-rcolorbrewer=1.1_2=mro343h889e2dd_0
  - r-readr=1.1.1=mro343h599a50d_0
  - r-readxl=1.0.0=mro343h599a50d_0
  - r-rematch=1.0.1=mro343h889e2dd_0
  - r-reprex=0.1.1=mro343h889e2dd_0
  - r-reshape2=1.4.3=mro343h599a50d_0
  - r-rlang=0.1.6=mro343h086d26f_0
  - r-rstudioapi=0.7=mro343h889e2dd_0
  - r-rvest=0.3.2=mro343h889e2dd_0
  - r-scales=0.5.0=mro343h599a50d_0
  - r-selectr=0.3_1=mro343h889e2dd_0
  - r-tibble=1.4.1=mro343h086d26f_0
  - r-tidyr=0.7.2=mro343h599a50d_0
  - r-tidyselect=0.2.3=mro343h599a50d_0
  - r-tidyverse=1.2.1=mro343h889e2dd_0
  - r-utf8=1.1.2=mro343h086d26f_0
  - r-viridislite=0.2.0=mro343h889e2dd_0
  - r-whisker=0.3_2=mro343h889e2dd_0
  - r-xml2=1.1.1=mro343h599a50d_0
  - ruamel_yaml=0.15.46=py36h14c3975_0
  - tqdm=4.28.1=py36h28b3542_0
  - zstd=1.3.7=h0b5b093_0
  - _r-mutex=1.0.0=mro_2
  - mro-base=3.4.3=h1c2f66e_1
  - mro-basics=3.4.3=0
  - r=3.4.3=mro343_0
  - r-backports=1.1.2=mro343h086d26f_0
  - r-base64enc=0.1_3=mro343h086d26f_0
  - r-boot=1.3_20=mro343_0
  - r-checkpoint=0.4.3=mro343_0
  - r-class=7.3_14=mro343_0
  - r-cluster=2.0.6=mro343_0
  - r-codetools=0.2_15=mro343_0
  - r-curl=3.1=mro343_0
  - r-deployrrserve=9.0.0=mro343_0
  - r-digest=0.6.13=mro343h086d26f_0
  - r-doparallel=1.0.12=mro343_0
  - r-evaluate=0.10.1=mro343h889e2dd_0
  - r-foreach=1.4.5=mro343_0
  - r-foreign=0.8_69=mro343_0
  - r-highr=0.6=mro343h889e2dd_0
  - r-htmltools=0.3.6=mro343h599a50d_0
  - r-iterators=1.0.9=mro343_0
  - r-jsonlite=1.5=mro343_0
  - r-kernsmooth=2.23_15=mro343_0
  - r-knitr=1.18=mro343h889e2dd_0
  - r-lattice=0.20_35=mro343_0
  - r-magrittr=1.5=mro343h889e2dd_0
  - r-markdown=0.8=mro343h086d26f_0
  - r-mass=7.3_47=mro343_0
  - r-matrix=1.2_12=mro343_0
  - r-mgcv=1.8_22=mro343_0
  - r-microsoftr=3.4.3.0097=mro343_0
  - r-mime=0.5=mro343h086d26f_0
  - r-nlme=3.1_131=mro343_0
  - r-nnet=7.3_12=mro343_0
  - r-png=0.1_7=mro343_0
  - r-r6=2.2.2=mro343_0
  - r-rcpp=0.12.14=mro343h599a50d_0
  - r-recommended=3.4.3=mro343_0
  - r-revoioq=8.0.9=mro343_0
  - r-revomods=11.0.0=mro343_0
  - r-revoutilsmath=10.0.1=mro343_0
  - r-rmarkdown=1.8=mro343h889e2dd_0
  - r-rpart=4.1_11=mro343_0
  - r-rprojroot=1.3_1=mro343h889e2dd_0
  - r-runit=0.4.26=mro343_0
  - r-spatial=7.3_11=mro343_0
  - r-stringi=1.1.6=mro343h599a50d_0
  - r-stringr=1.2.0=mro343h889e2dd_0
  - r-survival=2.41_3=mro343_0
  - r-yaml=2.1.16=mro343h086d26f_0
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.0.1
    - libarchive-c==2.8
    - lief==0.9.0
    - matplotlib==2.2.2
    - numexpr==2.6.5
    - pyparsing==2.2.0
    - table==0.0.4
    - tables==3.4.3
prefix: /home/wouters/miniconda3/envs/rosettapipeline

